export const demoPatients = [
  {
    _id: "demo1",
    srNo: 1,
    date: "2026-08-01",
    patientName: "Ahmed Raza",
    age: 34,
    houseAddress: "Street 4, Madina Town",
    disease: "Fever",
    medicine: "Panadol",
    amount: 500,
    diseaseDetails: [
      { _id: "d1", date: "2026-08-01", disease: "Fever", medicine: "Panadol", note: "Mild fever" },
    ],
  },
  {
    _id: "demo2",
    srNo: 2,
    date: "2026-08-03",
    patientName: "Sana Iqbal",
    age: 27,
    houseAddress: "Gulberg, Faisalabad",
    disease: "Migraine",
    medicine: "Disprin",
    amount: 800,
    diseaseDetails: [],
  },
  {
    _id: "demo3",
    srNo: 3,
    date: "2026-08-05",
    patientName: "Bilal Hussain",
    age: 45,
    houseAddress: "Peoples Colony",
    disease: "Blood Pressure",
    medicine: "Amlodipine",
    amount: 1200,
    diseaseDetails: [
      { _id: "d2", date: "2026-08-05", disease: "Blood Pressure", medicine: "Amlodipine", note: "Follow-up" },
    ],
  },
  {
    _id: "demo4",
    srNo: 4,
    date: "2026-08-06",
    patientName: "Ayesha Noor",
    age: 19,
    houseAddress: "Susan Road",
    disease: "Cough",
    medicine: "Syrup Tixylix",
    amount: 350,
    diseaseDetails: [],
  },
];
